os: Windows Server 2012 R2

platform:
  - x86
  - x64

configuration:
  - Release

branches:
  only:
    - master

install:
  - git fetch --tags
  - echo APPVEYOR_REPO_TAG_NAME %APPVEYOR_REPO_TAG_NAME%
  - echo APPVEYOR_REPO_TAG %APPVEYOR_REPO_TAG%
  - echo appveyor_repo_tag_name %appveyor_repo_tag_name%
  - echo appveyor_repo_tag %appveyor_repo_tag%
  - ps: echo $env:platform
  - ps: Get-ChildItem "C:\Qt\5.10\"
  - ps: if ($env:platform -eq 'x64') {$env:QTDIR = "C:\Qt\5.10\msvc2015_64"}
  - ps: if ($env:platform -eq 'x86') {$env:QTDIR = "C:\Qt\5.10\msvc2015"}
  - ps: echo $env:QTDIR
  - ps: Get-ChildItem C:\Qt\5.10
  - set PATH=%PATH%;%QTDIR%\bin


  - ps: Get-ChildItem "C:\Program Files (x86)\"
  - ps: Get-ChildItem "C:\Program Files\"
#  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /%PLATFORM% /Release'

  - ps: cd "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC"
  - echo %PLATFORM%
#  - cmd: if "%PLATFORM%" == "x64" call vcvarsall.bat amd64
  - if "%PLATFORM%" == "x86" call vcvarsall.bat x86
  - if "%PLATFORM%" == "x64" call vcvarsall.bat amd64
#  - ps: if ($env:platform -eq 'x64') {.\vcvarsall.bat amd64}
#  - ps: if ($env:platform -eq 'x86') {.\vcvarsall.bat x86}
  #- cmd: vcvarsall amd64
  - ps: cd "C:\projects\fmit"


  - ps: New-Item -ItemType directory -Name lib
  - ps: cd lib

  - ps: echo "Install FFTW3"
  - ps: if ($env:platform -eq 'x64') {$libfft = "fftw-3.3.4-dll64"}
  - ps: if ($env:platform -eq 'x86') {$libfft = "fftw-3.3.4-dll32"}
  - ps: echo $libfft
  - ps: New-Item -ItemType directory -Name $libfft | Out-Null
  - ps: cd $libfft
#  - echo %CD%
  - ps: Invoke-WebRequest "ftp://ftp.fftw.org/pub/fftw/$libfft.zip" -OutFile "$libfft.zip"
  - ps: Get-ChildItem .
#  - appveyor DownloadFile "ftp://ftp.fftw.org/pub/fftw/$libfft.zip"
  - ps: 7z x "$libfft.zip" -y
  - ps: lib /machine:$env:platform /def:libfftw3-3.def
  - ps: Get-ChildItem .
  - ps: cd ..
  - ps: Move-Item "$libfft" libfft
#  - ps: Get-ChildItem C:\projects\dfasma\lib\fftw-3.3.4-dll32
#  - ps: lib /MACHINE:X86 /def:libfftw3-3.def # Needed only for MSVC (lib is still unrecognized command)

  - ps: cd ..

  - choco install -y InnoSetup

  - ps: cd "c:\projects\fmit"

build_script:
  - qmake "FFT_LIBDIR=C:\projects\fmit\lib\libfft" fmit.pro
#  - ps: Get-ChildItem .
  - set PATH=%PATH%;C:\Qt\Tools\QtCreator\bin
  - C:\Qt\Tools\QtCreator\bin\jom.exe -f Makefile.Release

# Build package
  - ps: Get-ChildItem c:\projects\fmit\lib
  - ps: Get-ChildItem c:\projects\fmit\lib\libfft
  - ps: .\distrib\package_windows_appveyor.ps1 $env:platform
  - ps: Move-Item distrib\fmit_*_win*.exe .
  - ps: Get-ChildItem .
  #- ps: $GITPROJECTVERSION = (git describe --tags --always) | Out-String
  #- ps: $GITPROJECTVERSION = $GITPROJECTVERSION -replace "`n|`r"
  #- ps: echo "Version $GITPROJECTVERSION"
  - echo APPVEYOR_REPO_TAG_NAME %APPVEYOR_REPO_TAG_NAME%
  - if defined APPVEYOR_REPO_TAG_NAME set RELEASEVERSION=%APPVEYOR_REPO_TAG_NAME:~1%
  - echo Version %RELEASEVERSION%


artifacts:
  - path: fmit_*_win*.exe
    name: newinstallers   # Reference used for deployment

deploy:
- provider: GitHub
  release: Version $(releaseversion)
  tag: $(appveyor_repo_tag_name)
  auth_token:
    secure: $(GITHUB_AUTH_TOKEN)
  artifact: newinstallers
  draft: true
  prerelease: false
  on:
    appveyor_repo_tag: true        # deploy on tag push only
    #branch: /v\d+\.\d+\.\d+/      # Doesn't work anymore
