os: Windows Server 2012 R2

platform:
  - x64

configuration:
  - Release

install:
  - set QTDIR=C:\Qt\5.4\msvc2013_64_opengl
  - set PATH=%PATH%;%QTDIR%\bin
  
  - ps: cd "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC"
#  - ps: Get-ChildItem .
  - cmd: vcvarsall amd64
  - ps: cd "C:\projects\fmit"

  - ps: New-Item -ItemType directory -Name lib
  - ps: cd lib
  
  - ps: New-Item -ItemType directory -Name fftw-3.3.4-dll64
  - ps: cd fftw-3.3.4-dll64
#  - echo %CD%
  - appveyor DownloadFile ftp://ftp.fftw.org/pub/fftw/fftw-3.3.4-dll64.zip
  - ps: 7z x fftw-3.3.4-dll64.zip -y
  - ps: lib /machine:x64 /def:libfftw3-3.def
  - ps: Get-ChildItem .
  - ps: cd ..
#  - ps: Get-ChildItem C:\projects\fmit\lib\fftw-3.3.4-dll32
#  - ps: lib /MACHINE:X86 /def:libfftw3-3.def # Needed only for MSVC (lib is still unrecognized command)

  - ps: New-Item -ItemType directory -Name freeglut-MSVC
  - ps: cd freeglut-MSVC
  - appveyor DownloadFile http://files.transmissionzero.co.uk/software/development/GLUT/freeglut-MSVC-3.0.0-1.mp.zip
  - ps: 7z x freeglut-MSVC-3.0.0-1.mp.zip -y
  - ps: cd ..
  
  - ps: cd ..

build_script:
  - qmake "FFT_LIBDIR=C:\projects\fmit\lib\fftw-3.3.4-dll64" "GLUT_LIBDIR=C:\projects\fmit\lib\freeglut-MSVC\freeglut" fmit.pro
#  - ps: Get-ChildItem .
  - set PATH=%PATH%;C:\Qt\Tools\QtCreator\bin
  - C:\Qt\Tools\QtCreator\bin\jom.exe -f Makefile.Release
